version: '3.3'
services:
  db:
    container_name: skip-data-db
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: skipdata
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -c max_connections=20

volumes:
  db:
    driver: local